[plugin]
repository = "https://github.com/rosella500/IslandWorkshopSolver.git"
commit = "51281f40f31517eea6d239043e2d7e1ef0684082"
owners = [
    "rosella500"
]
project_path = "IslandWorkshopSolver"
changelog = "Handle running plugin on D7 with or without current week's data"
